# NUMPY

In [1]:
pip install numpy

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [11]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.



CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/win-64'




In [17]:
import numpy as ntc

In [18]:
print (ntc.__version__)


1.21.5


In [19]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
print(type(arr))

<class 'numpy.ndarray'>


In [23]:
print (np.amin(arr))

1


In [24]:
print (np.amax(arr))

10


In [26]:
print (np.mean(arr))

5.5


In [27]:
print (np.median(arr))

5.5


In [28]:
print (np.ptp(arr))

9


In [29]:
print (np.std(arr))

2.8722813232690143


In [30]:
print (np.var(arr))

8.25


In [31]:
print (np.average(arr))

5.5


In [48]:
print (np.percentile(arr,5))

1.45


# Numpy numerical python  

In [55]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
#diamensoin of the array

print(arr.ndim)

2


In [58]:
#shape of the array

print(arr.shape)

(2, 5)


In [59]:
#diamensoin of the array

print(type(arr))

<class 'numpy.ndarray'>


In [60]:
#diamensoin of the array

print(arr.data)

# # Random number generator using numpy

In [80]:
from numpy import random
x= random.randint(100)
print(x)

9


In [78]:
#generate random float

x = random.rand(100)
print(x)

[0.92741741 0.02034876 0.87740481 0.95465202 0.87582195 0.2191903
 0.13819433 0.43938424 0.64432678 0.41565665 0.42667247 0.41500884
 0.69822462 0.5883023  0.16179951 0.16919539 0.5354816  0.3402453
 0.52134239 0.58141659 0.36295717 0.79481951 0.14655423 0.81228585
 0.79394433 0.25352346 0.94604241 0.40136369 0.42501061 0.62827943
 0.6086068  0.44015405 0.57611016 0.80673237 0.63024778 0.6978589
 0.27916956 0.23671095 0.41161319 0.62286328 0.33790673 0.63442381
 0.58952215 0.44140373 0.0642242  0.05020656 0.05150218 0.08694142
 0.31350591 0.02943608 0.67608661 0.21539833 0.99208203 0.99535405
 0.52954602 0.08172928 0.64092837 0.58523199 0.13926505 0.62400971
 0.28938426 0.21232907 0.59150604 0.54034867 0.88487696 0.78522413
 0.02788093 0.83186708 0.09687731 0.17611222 0.97402292 0.72562113
 0.72289748 0.37414835 0.53702384 0.05589629 0.81634938 0.28918524
 0.261575   0.92026351 0.96079247 0.67509677 0.33739586 0.25904635
 0.70477003 0.78070836 0.37563869 0.03322972 0.34070962 0.5157701

In [89]:
#generate random array


from numpy import random
x= random.randint(100,size=(10))
print(x)

[27 75 21 20 54 48 79 53 11 36]


In [93]:
#generate random array


from numpy import random
x= random.randint(100,size=(10,25))
print(x)

[[86 82 62 91 17 11 30 29 88 85 76 18 22 44 70 63 24 27 51 20 33 70 28 92
  25]
 [19 57 84 92 26 56 64 58 72 40 26 43 18 91 78 19 54 10 53 37 59 10 18 94
   8]
 [10 15 92  8 39 44 35 69  9 87 17 83 71  6 65 82 20 40 38 43 34 24 37 70
  92]
 [88 67 24 95 54 30 82 76 50 82 31 16 82 15 23  7 74 24 33 12 38 42 24  9
  88]
 [79 87 19 37 90 77 65 85 43 92 91 17 26 40 86 60 17 37 25 34  2  8 92 33
  10]
 [64 30 93 95 20 92 68 88 60 61 19 49 31 31 12 60 63 57 54 48 35 38 59 57
  90]
 [42  0 86 64 52 24 96 58 86 16 21  5 78 96 48  0 33 21  8 87  2 11 92  0
  83]
 [11 46 93 20 34 59 19 41 29 90 56 52  8 84 10 59 19 50 56 28 20 97  8 18
  36]
 [27 82 52 28 26 58 82  3 85 71 59 22 93 64 29 55 29 56 58 28 75 45 46 85
  37]
 [ 7 72 94  2 50 64 23  1 59 15 34 29 79 28 45 13 15 72 86 97 40 23 40 71
  14]]


In [94]:
from numpy import random
random.seed(101)
x= random.randint(100,size=(10,25))
print(x)

[[95 11 81 70 63 87 75  9 77 40  4 63 40 60 92 64  5 12 93 40 49 83  8 29
  59]
 [34 44 72 19 10 76 95 87  0 73  8 62 36 83 99 28 63  7 10 52 56 38 73 52
  18]
 [71 15 44  0 12 17 75 79 97 93 24 36 63 19 35 30 10 60 20 27  8 86 26 87
  46]
 [47 54 86  9 45  2 18 58 92 11 10 94 35 28  3 83 84 47 14 69 60 69 51  6
  88]
 [71 68 23 35 79 98 67 82 57 77 46  3 46 29 86 21 21 81 23 94 71 20 27 75
   5]
 [49 86 89 63 82 77  3 56 14 49 87 52 13 47 49 24 20 64 52 60 47 29 60 53
  11]
 [40 91 45 97 24 36 38  9 52 67 43  1 79 68 68 61 18 51 14 28 17 87 46 52
  16]
 [70 71 84 10 62 96 57 23 86 85 26 76 66 54 17 65 57 89  2 80 50 66 88 79
  93]
 [ 6 92 42 22 20 25 97 54 71 72 80 93 64 63 80 38 45 35 25 95 75 72 11 76
  79]
 [50 22 59 66  1 34 37 57 35 42 44 49 31 79 85  3 55 73 93 94 99 40 54 88
  94]]


In [95]:
from numpy import random
random.seed(101)
x= random.randint(100,size=(10,25))
print(x)

[[95 11 81 70 63 87 75  9 77 40  4 63 40 60 92 64  5 12 93 40 49 83  8 29
  59]
 [34 44 72 19 10 76 95 87  0 73  8 62 36 83 99 28 63  7 10 52 56 38 73 52
  18]
 [71 15 44  0 12 17 75 79 97 93 24 36 63 19 35 30 10 60 20 27  8 86 26 87
  46]
 [47 54 86  9 45  2 18 58 92 11 10 94 35 28  3 83 84 47 14 69 60 69 51  6
  88]
 [71 68 23 35 79 98 67 82 57 77 46  3 46 29 86 21 21 81 23 94 71 20 27 75
   5]
 [49 86 89 63 82 77  3 56 14 49 87 52 13 47 49 24 20 64 52 60 47 29 60 53
  11]
 [40 91 45 97 24 36 38  9 52 67 43  1 79 68 68 61 18 51 14 28 17 87 46 52
  16]
 [70 71 84 10 62 96 57 23 86 85 26 76 66 54 17 65 57 89  2 80 50 66 88 79
  93]
 [ 6 92 42 22 20 25 97 54 71 72 80 93 64 63 80 38 45 35 25 95 75 72 11 76
  79]
 [50 22 59 66  1 34 37 57 35 42 44 49 31 79 85  3 55 73 93 94 99 40 54 88
  94]]


In [102]:
#import numpy

import numpy as np
#creating 1-D LIST 
list1 = [1,2,3]    
   
#creating 1_D List vertical
list2 = [[10],
        [20],
        [30]]

vector1 = np.array(list1)
vector2 = np.array(list2)

print("Horizontal vector")
print(vector1)

print("-------------------")

print("vertical vector")
print(vector2)

print("-------------------")

Horizontal vector
[1 2 3]
-------------------
vertical vector
[[10]
 [20]
 [30]]
-------------------


In [104]:
a= np.matrix ('1 2 ; 3 4')
print ( "via string input : \n" , a, "\n\n")
b= np.matrix([[5,6,7], [4,6]])
print("via array-like input :\n", b)

via string input : 
 [[1 2]
 [3 4]] 


via array-like input :
 [[list([5, 6, 7]) list([4, 6])]]


# # practical

In [105]:
a = 5

b = [[6,7],
     [8,9]]

print(np.dot(a,b))


[[30 35]
 [40 45]]


In [108]:
a = [[6,7],
    [8,9]]

b = [[2,3],
    [4,5]]
print(np.dot(a,b))
print("-------------------")
print(np.dot(b,a))

[[40 53]
 [52 69]]
-------------------
[[36 41]
 [64 73]]


In [114]:
a = [[20,30],
    [80,90]]

b = [[20,30],
    [40,50]]
print(np.dot(a,b))
print("-------------------")
print(np.dot(b,a))

[[1600 2100]
 [5200 6900]]
-------------------
[[2800 3300]
 [4800 5700]]


In [120]:
A= ([1,2,3],[4,5,6],[7,8,9,])
np.transpose(A)


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# #%%%%%


In [3]:
import numpy as np
data = [12,13,15,70,74,72,10,20,32,1665,33,562,520,54,21,13,116,463,0,3]
 #first 
Q1 = np.median(data[:10])
print(Q1,'\n')
#third
Q3 = np.median(data[10:])
print(Q3,'\n')

IQR = Q3-Q1
print("IQR = Q3-Q1 =",IQR)

26.0 

43.5 

IQR = Q3-Q1 = 17.5


# #2.10

In [19]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])

a*b

array([2., 4., 6.])

In [21]:
a=np.array([1.0,2.0,3.0])
b=2.0
a+b

array([3., 4., 5.])

In [22]:
a=np.array([111.0,2241.0,35245.0])
b=np.array([2.0,2.0,2.0])
a*b

array([  222.,  4482., 70490.])

In [23]:
a=np.array([111222.0,2231241.0,3524445.0])
b=np.array([254758331.0,2131.0,2131.0])
a*b

array([2.83347311e+13, 4.75477457e+09, 7.51059230e+09])

## calculate bmi

In [6]:
#heights of players 

hg_in = [61,45,20,78,40,22,52,75,43,42,47]
#convert into num

ht_np = np.array(hg_in)

#convert height from inch to meter by exposing it to .0245
ht_np = ht_np*.0245

ht_np

array([1.4945, 1.1025, 0.49  , 1.911 , 0.98  , 0.539 , 1.274 , 1.8375,
       1.0535, 1.029 , 1.1515])

In [8]:
#weight of players

wt_pd = [70,100,50,65,75,60,75,10,65,90,55]
#convert into in array
wt_pd = np.array(wt_pd)

#convert weight 0.45

wt_np = wt_pd*0.45

wt_np





array([31.5 , 45.  , 22.5 , 29.25, 33.75, 27.  , 33.75,  4.5 , 29.25,
       40.5 , 24.75])

In [9]:
#bmi calculation
BMI=wt_np/(ht_np**2)
BMI

array([14.10323411, 37.02161137, 93.71095377,  8.00948323, 35.14160766,
       92.93648308, 20.79385069,  1.33277801, 26.35462194, 38.24936889,
       18.66583054])

In [10]:
#bmi calculation
BMI=wt_np/(ht_np/2)
BMI

array([ 42.15456674,  81.63265306,  91.83673469,  30.6122449 ,
        68.87755102, 100.18552876,  52.98273155,   4.89795918,
        55.52918842,  78.71720117,  42.98740773])

In [11]:
BMI[-1]

42.98740772904907

In [12]:
BMI[BMI<21]

array([4.89795918])

In [15]:
players = np.array([wt_pd,ht_np])
players


array([[ 70.    , 100.    ,  50.    ,  65.    ,  75.    ,  60.    ,
         75.    ,  10.    ,  65.    ,  90.    ,  55.    ],
       [  1.4945,   1.1025,   0.49  ,   1.911 ,   0.98  ,   0.539 ,
          1.274 ,   1.8375,   1.0535,   1.029 ,   1.1515]])

In [20]:
players[0][5]

60.0

In [22]:
players[1][2]

0.49

In [23]:
players[1]

array([1.4945, 1.1025, 0.49  , 1.911 , 0.98  , 0.539 , 1.274 , 1.8375,
       1.0535, 1.029 , 1.1515])

In [29]:
#teamspase

pT = players.transpose()
pT

array([[ 70.    ,   1.4945],
       [100.    ,   1.1025],
       [ 50.    ,   0.49  ],
       [ 65.    ,   1.911 ],
       [ 75.    ,   0.98  ],
       [ 60.    ,   0.539 ],
       [ 75.    ,   1.274 ],
       [ 10.    ,   1.8375],
       [ 65.    ,   1.0535],
       [ 90.    ,   1.029 ],
       [ 55.    ,   1.1515]])

In [31]:
pT.shape

(11, 2)

In [43]:
#stastical and mathematical function on player data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))

print(np.std(wt_np))

print(np.corrcoef(wt_np ,ht_np))

29.25
29.25
321.75
10.016463720023422
[[ 1.         -0.26799232]
 [-0.26799232  1.        ]]


# #homework find the volume of our degree bulding

In [1]:
#length of classroom 
import numpy as np
len_m = [61,45,20,78,40,22,52,75,43,42,47]
#convert into num

len_np = np.array(len_m)


len_np

array([61, 45, 20, 78, 40, 22, 52, 75, 43, 42, 47])

In [3]:
#width of classroom 
wid_m = [11,25,20,78,30,22,52,45,43,42,47]
#convert into num

wid_np = np.array(wid_m)


wid_np

array([11, 25, 20, 78, 30, 22, 52, 45, 43, 42, 47])

In [5]:
#height of classroom 
ht_m = [11,25,20,78,30,22,52,45,43,42,47]
#convert into num

ht_np = np.array(ht_m)


ht_np

array([11, 25, 20, 78, 30, 22, 52, 45, 43, 42, 47])

In [8]:
#volume of classroom is

volume = len_np*wid_np*ht_np
volume

array([  7381,  28125,   8000, 474552,  36000,  10648, 140608, 151875,
        79507,  74088, 103823])

# #2homework find the volume of our degree bulding


In [7]:
#length of classroom 
import numpy as np
len_m = [61,25,20,78,40,62,32,75,43,42,25]
#convert into num

len_np = np.array(len_m)


len_np

array([61, 25, 20, 78, 40, 62, 32, 75, 43, 42, 25])

In [8]:
#width of classroom 
wid_m = [11,25,20,78,30,22,52,45,43,42,47]
#convert into num

wid_np = np.array(wid_m)


wid_np

array([11, 25, 20, 78, 30, 22, 52, 45, 43, 42, 47])

In [9]:
#height of classroom 
ht_m = [11,25,20,78,30,22,52,45,43,42,47]
#convert into num

ht_np = np.array(ht_m)


ht_np

array([11, 25, 20, 78, 30, 22, 52, 45, 43, 42, 47])

In [10]:
#volume of classroom is

volume = len_np*wid_np*ht_np
volume

array([  7381,  15625,   8000, 474552,  36000,  30008,  86528, 151875,
        79507,  74088,  55225])

In [32]:
#length of classroom 
import numpy as np
len_m = [61,25,20,78,40,62,32,75,43,42,25]
#convert into num

len_np = np.array(len_m)


len_np

#width of classroom 
wid_m = [11,25,20,78,30,22,52,45,43,42,47]
#convert into num

wid_np = np.array(wid_m)


wid_np


#height of classroom 
ht_m = [11,25,20,78,30,22,52,45,43,42,47]
#convert into num

ht_np = np.array(ht_m)


ht_np

#volume of classroom is
volume = len_np+wid_np+ht_np
volume

array([ 83,  75,  60, 234, 100, 106, 136, 165, 129, 126, 119])

In [31]:
print(np.mean(len_np))

print(np.median(len_np))

print(np.sum(len_np))

print(np.std(len_np))

print(np.corrcoef(len_np ,ht_np))

45.72727272727273
42.0
503
19.44732236343703
[[1.         0.31258868]
 [0.31258868 1.        ]]


In [34]:
4 variable
string"
list[]
tuple()
array [][[],[]],([],[])
,

SyntaxError: invalid syntax (2989150523.py, line 1)